# Permalinks
permalink:        pretty
markdown:         kramdown

# Setup
url:              https://YichengPu.github.io

# Set to '' in case of hosting on `http://<your-github-name>.github.io`
baseurl:          ''

title:            YichengPu

# Markdown enabled, however don't use more than one paragraph (enforced by `>`)
description:       >
  借我那把枪吧 或者借我五毛钱
  南方的江山太娇媚 容易遮上我的眼

# The tags listed as entries in the sidebar
sidebar_tags:     [UCTC, Trading]

# Fallback image and color if not overwritten for tag or post
image:            /public/img/south-western.jpg
color:            '#A85641'

author:
  name:           'Yicheng Pu'

  # Setting social media usernames will add icons at the bottom of the sidebar
  twitter:        
  github:         YichengPu

  # Setting a disqus username will enable the comment section
  disqus:         ypu4

  # This photo will be used in the about section
  photo:          http://i4.piimg.com/567571/43913612226f0b5c.jpg

  # Markdown enabled, can use multiple paragraphs (enabled by `|`)
  about:          |
  Hi, I'm Yicheng Pu.
   


kramdown:
  math_engine: mathjax
  math_engine_opts:
    preview: true
